language: node_js
node_js:
  - 14
scripts:
  - eslint 'src/**'
  - npm run test:coveralls
services:
  - postgresql
addons:
  postgresql: "9.4"
env:
  global:
    - PGPORT=5432
    - DB_NAME=cleannodeapi
    - PG_URL=postgresql://postgres:@localhost:5432/cleannodeapi
before_script:
  - psql -c 'create database cleannodeapi;' -U postgres
  - psql --dbname=cleannodeapi --file=./sql/scripts/create-tables.sql postgres
