language: node_js
node_js:
  - 14
scripts:
  - eslint 'src/**'
  - npm run test:coveralls
services:
  - postgresql
addons:
  postgresql: "9.4"
env:
  global:
    - PGPORT=5432
    - DB_NAME=clean-node-api
    - PG_URL=postgresql://postgres:@localhost:5432/clean-node-api
before_script:
  - psql -c 'create database clean-node-api;' -U postgres
  - psql --dbname=clean-node-api --file=sql/create-tables.sql