version: '3'
services: 
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
  postgres:
    container_name: postgres-container
    image: postgres:13
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clean-node-api
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "vitor@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment: 
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
      - PG_URL=postgresql://postgres:postgres@postgres:5432/clean-node-api
    volumes: 
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    depends_on: 
      - mongo
      - postgres
    links: 
      - mongo
      - postgres

